# External programms
PYTHON				:= python3

# FTST test setup
FTST_SRCS			?=
FTST_DIR			?=	ftst-unit-test-framework/
FTST_TARGET			?=


FTST_TEST_GENERATOR	=	${FTST_DIR}gen_test_main.py
FTST_TEST_RUNNER_SRC =	ftst_test_runner.c

FTST_INC			=	${FTST_DIR}include/
FTST_H_INC			=	${addprefix -I , ${FTST_INC}}

FTST_SILENT_MODE	?=	1
FTST_SILENT			=	-D FTST_SILENT=${FTST_SILENT_MODE} 

FTST_ALLOC_MODE		?=	1
FTST_ALLOC_TEST		=	-ldl -D FTST_ALLOC_TEST=${FTST_ALLOC_MODE}

FTST_COLOR_MODE		?=	1
FTST_COLOR			=	-D FTST_COLOR=${FTST_COLOR_MODE}

FTST_FLAGS			=	${FTST_COLOR} ${FTST_ALLOC_TEST} ${FTST_SILENT} ${FTST_H_INC}

# Pretty print
FTST_COLOR_RED		= \x1b[31m
FTST_COLOR_GREEN	= \x1b[32m
FTST_COLOR_YELLOW	= \x1b[33m
FTST_COLOR_BLUE		= \x1b[34m
FTST_COLOR_MAGENTA	= \x1b[35m
FTST_COLOR_CYAN		= \x1b[36m
FTST_COLOR_RESET	= \x1b[0m
FTST_RESET_LINE		= \033[A\033[2K

FTST_PRETTY_DONE	= [${FTST_COLOR_GREEN}✓${FTST_COLOR_RESET}]
FTST_PRETTY_FAIL	= [${FTST_COLOR_RED}✕${FTST_COLOR_RESET}]

FTST_PRETTY_STATUS	= "%b%b ${FTST_COLOR_YELLOW}%b${FTST_COLOR_RESET} %b\n"

# FTST test setup
FTST_CC				?=	gcc	
FTST_COMPILE_FLAGS	?=
FTST_INC			=	include/
FTST_TEST_SRCS		?=
FTST_SRCS			?=
FTST_COMPILE_MODE	?=

FTST_SILENT			?=	1
FTST_ALLOC_TEST		?=	1
FTST_COLOR			?=	1
FTST_ERROR_MESSAGE	?=	1

FTST_COLOR_MODE			=	-D FTST_COLOR=${FTST_COLOR}
FTST_SILENT_MODE		=	-D FTST_SILENT=${FTST_SILENT_MODE} 
FTST_ERROR_MESSAGE_MODE	=	-D FTST_ERROR_MESSAGE=${FTST_ERROR_MESSAGE} 
FTST_ALLOC_MODE			=	-ldl -D FTST_ALLOC_TEST=${FTST_ALLOC_MODE}

FTST_TEST_GENERATOR		=	gen_test_main.py
FTST_TEST_RUNNER_SRC	=	ftst_test_runner.c

FTST_H_INC			=	${addprefix -I , ${FTST_INC}}
FTST_FLAGS			=	${FTST_ERROR_MESSAGE_MODE} ${FTST_COLOR_MODE} ${FTST_ALLOC_MODE} ${FTST_SILENT_MODE} ${FTST_H_INC}
FTST_EXE			=	ftst.out

.INTERMEDIATE: ${FTST_TEST_RUNNER_SRC}
${FTST_TEST_RUNNER_SRC}: ${FTST_SRCS}
			@${PYTHON} ${FTST_TEST_GENERATOR} ${FTST_SRCS}

.INTERMEDIATE: ${FTST_EXE}
${FTST_EXE}:	${FTST_TEST_RUNNER_SRC} ${FTST_TARGET}
			@${CC} ${FTST_FLAGS} ${FTST_H_INC} ${FTST_SRCS} ${FTST_TEST_RUNNER_SRC} -o ${FTST_EXE} ${FTST_TARGET}