# External programms
PYTHON		:= python3

# FTST test setup
FTST_SRCS			?=
FTST_DIR			?=	ftst-unit-test-framework/
FTST_TARGET			?=


FTST_TEST_GENERATOR	=	${FTST_DIR}gen_test_main.py
FTST_TEST_RUNNER_SRC =	ftst_test_runner.c

FTST_INC			=	${FTST_DIR}include/
FTST_H_INC			=	${addprefix -I , ${FTST_INC}}

FTST_SILENT_MODE	?=	1
FTST_SILENT			=	-D FTST_SILENT=${FTST_SILENT_MODE} 

FTST_ALLOC_MODE		?=	1
FTST_ALLOC_TEST		=	-ldl -D FTST_ALLOC_TEST=${FTST_ALLOC_MODE}

FTST_COLOR_MODE		?=	1
FTST_COLOR			=	-D FTST_COLOR=${FTST_COLOR_MODE}

FTST_FLAGS			=	${FTST_COLOR} ${FTST_ALLOC_TEST} ${FTST_SILENT}
FTST_EXE			=	ftst.out

.INTERMEDIATE: ${FTST_TEST_RUNNER_SRC}
${FTST_TEST_RUNNER_SRC}: ${FTST_SRCS}
			@${PYTHON} ${FTST_TEST_GENERATOR} ${FTST_SRCS}

.INTERMEDIATE: ${FTST_EXE}
${FTST_EXE}:	${FTST_TEST_RUNNER_SRC}
			@${CC} ${FTST_FLAGS} ${FTST_H_INC} ${FTST_SRCS} ${FTST_TEST_RUNNER_SRC} -o ${FTST_EXE} ${FTST_TARGET}
